"""Build the reviewed, local Portuguese label catalogue; source IDs stay unchanged."""
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
D={}; A={}; N={}; missing=set()
def rows(text,target):
    for row in text.strip().splitlines():
        if row.strip():
            k,v=row.split('=',1);target[k.strip()]=v.strip()
rows('''
heart=coração|m
liver=fígado|m
brain=encéfalo|m
stomach=estômago|m
spleen=baço|m
pancreas=pâncreas|m
urinary bladder=bexiga urinária|f
bladder=bexiga|f
trachea=traqueia|f
diaphragm=diafragma|m
esophagus=esôfago|m
oesophagus=esôfago|m
gallbladder=vesícula biliar|f
kidney=rim|m
duodenum=duodeno|m
testis=testículo|m
skin=pele|f
prostate=próstata|f
adrenal gland=glândula suprarrenal|f
pituitary gland=hipófise|f
pineal body=glândula pineal|f
thyroid gland=glândula tireoide|f
thymus=timo|m
lung=pulmão|m
small intestine=intestino delgado|m
large intestine=intestino grosso|m
intestine=intestino|m
jejunum=jejuno|m
ileum=íleo|m
cecum=ceco|m
appendix=apêndice|m
rectum=reto|m
colon=cólon|m
sigmoid colon=cólon sigmoide|m
ureter=ureter|m
urethra=uretra|f
epididymis=epidídimo|m
deferent duct=ducto deferente|m
seminal vesicle=vesícula seminal|f
penis=pênis|m
glans penis=glande do pênis|f
corpus cavernosum=corpo cavernoso|m
corpus spongiosum=corpo esponjoso|m
gingiva=gengiva|f
upper jaw=maxila|f
lower jaw=mandíbula|f
maxilla=maxila|f
mandible=mandíbula|f
tooth=dente|m
incisor tooth=dente incisivo|m
canine tooth=dente canino|m
premolar tooth=dente pré-molar|m
molar tooth=dente molar|m
head=cabeça|f
neck=pescoço|m
body=corpo|m
human body=corpo humano|m
trunk=tronco|m
thorax=tórax|m
chest=tórax|m
abdomen=abdome|m
pelvis=pelve|f
hip=quadril|m
hip bone=osso do quadril|m
shoulder=ombro|m
arm=braço|m
forearm=antebraço|m
hand=mão|f
wrist=punho|m
thigh=coxa|f
leg=perna|f
foot=pé|m
knee=joelho|m
finger=dedo da mão|m
toe=dedo do pé|m
index finger=dedo indicador|m
middle finger=dedo médio|m
ring finger=dedo anular|m
little finger=dedo mínimo da mão|m
little toe=dedo mínimo do pé|m
big toe=hálux|m
thumb=polegar|m
upper limb=membro superior|m
lower limb=membro inferior|m
pectoral girdle=cintura escapular|f
pelvic girdle=cintura pélvica|f
femur=fêmur|m
tibia=tíbia|f
fibula=fíbula|f
humerus=úmero|m
radius=rádio|m
ulna=ulna|f
clavicle=clavícula|f
scapula=escápula|f
sternum=esterno|m
manubrium=manúbrio|m
sacrum=sacro|m
atlas=atlas|m
axis=áxis|m
ethmoid=etmoide|m
vomer=vômer|m
patella=patela|f
talus=tálus|m
calcaneus=calcâneo|m
navicular=navicular|m
capitate=capitato|m
hamate=hamato|m
lunate=semilunar|m
pisiform=pisiforme|m
scaphoid=escafoide|m
trapezium=trapézio|m
trapezoid=trapezoide|m
triquetral=piramidal|m
skull=crânio|m
basicranium=base do crânio|f
neurocranium=neurocrânio|m
viscerocranium=viscerocrânio|m
brainstem=tronco encefálico|m
spinal cord=medula espinal|f
neuraxis=neuroeixo|m
forebrain=prosencéfalo|m
hindbrain=rombencéfalo|m
midbrain=mesencéfalo|m
telencephalon=telencéfalo|m
diencephalon=diencéfalo|m
metencephalon=metencéfalo|m
cerebellum=cerebelo|m
pons=ponte|f
medulla oblongata=bulbo|m
medulla=medula|f
thalamus=tálamo|m
hypothalamus=hipotálamo|m
epithalamus=epitálamo|m
hippocampus=hipocampo|m
amygdala=amígdala cerebral|f
globus pallidus=globo pálido|m
putamen=putâmen|m
insula=ínsula|f
habenula=habênula|f
corpus callosum=corpo caloso|m
fornix=fórnice|m
lamina terminalis=lâmina terminal|f
stria terminalis=estria terminal|f
tuber cinereum=túber cinéreo|m
conus medullaris=cone medular|m
tentorium cerebelli=tenda do cerebelo|f
dura mater=dura-máter|f
white matter=substância branca|f
gray matter=substância cinzenta|f
optic chiasm=quiasma óptico|m
optic tract=trato óptico|m
eye=olho|m
eyeball=bulbo do olho|m
lens=cristalino|m
retina=retina|f
cornea=córnea|f
sclera=esclera|f
choroid=coroide|f
iris=íris|f
vitreous body=corpo vítreo|m
corona ciliaris=coroa ciliar|f
lacrimal lake=lago lacrimal|m
orbit=órbita|f
eyelid=pálpebra|f
eyebrow=sobrancelha|f
nose=nariz|m
mouth=boca|f
lip=lábio|m
tongue=língua|f
uvula=úvula|f
soft palate=palato mole|m
pharynx=faringe|f
laryngopharynx=laringofaringe|f
larynx=laringe|f
epiglottis=epiglote|f
face=face|f
cheek=bochecha|f
ear=orelha|f
hair=pelo|m
hairs=pelos|mp
pubic hair=pelos pubianos|mp
perineum=períneo|m
mons pubis=monte do púbis|m
peritoneum=peritônio|m
mesentery=mesentério|m
mesocolon=mesocólon|m
mesoappendix=mesoapêndice|m
mediastinum=mediastino|m
aorta=aorta|f
vena cava=veia cava|f
linea alba=linha alba|f
taenia coli=tênia do cólon|f
taenia libera=tênia livre|f
taenia mesocolica=tênia mesocólica|f
taenia omentalis=tênia omental|f
conus elasticus=cone elástico|m
superior rectus=músculo reto superior|m
inferior rectus=músculo reto inferior|m
medial rectus=músculo reto medial|m
lateral rectus=músculo reto lateral|m
superior oblique=músculo oblíquo superior|m
inferior oblique=músculo oblíquo inferior|m
oblique arytenoid=músculo aritenóideo oblíquo|m
transverse arytenoid=músculo aritenóideo transverso|m
lateral crico-arytenoid=músculo cricoaritenóideo lateral|m
posterior crico-arytenoid=músculo cricoaritenóideo posterior|m
thyro-arytenoid=músculo tireoaritenóideo|m
hemiliver=metade do fígado|f
''',D)
rows('''
artery=artéria|f
arteries=artérias|fp
vein=veia|f
veins=veias|fp
nerve=nervo|m
muscle=músculo|m
bone=osso|m
rib=costela|f
vertebra=vértebra|f
vertebrae=vértebras|fp
phalanx=falange|f
cartilage=cartilagem|f
ligament=ligamento|m
branch=ramo|m
branches=ramos|mp
tributary=tributária|f
tree=árvore|f
trunk=tronco|m
part=parte|f
parts=partes|fp
segment=segmento|m
subdivision=subdivisão|f
division=divisão|f
set=conjunto|m
wall=parede|f
head=cabeça|f
body=corpo|m
arch=arco|m
gyrus=giro|m
sulcus=sulco|m
ventricle=ventrículo|m
atrium=átrio|m
chamber=câmara|f
cavity=cavidade|f
valve=valva|f
cusp=cúspide|f
leaflet=folheto|m
leaf=folheto|m
septum=septo|m
duct=ducto|m
gland=glândula|f
lobe=lobo|m
lobule=lóbulo|m
region=região|f
zone=zona|f
sector=setor|m
subsector=subsetor|m
organ=órgão|m
organs=órgãos|mp
component=componente|m
cluster=agrupamento|m
clusters=agrupamentos|mp
system=sistema|m
tissue=tecido|m
membrane=membrana|f
layer=camada|f
portion=porção|f
fascia=fáscia|f
tendon=tendão|m
retinaculum=retináculo|m
raphe=rafe|f
ring=anel|m
ganglion=gânglio|m
nucleus=núcleo|m
colliculus=colículo|m
brachium=braço|m
peduncle=pedúnculo|m
tract=trato|m
hemisphere=hemisfério|m
commissure=comissura|f
capsule=cápsula|f
plexus=plexo|m
chiasm=quiasma|m
foramen=forame|m
aqueduct=aqueduto|m
canal=canal|m
canaliculus=canalículo|m
sinus=seio|m
sac=saco|m
plate=lâmina|f
lamina=lâmina|f
stria=estria|f
fossa=fossa|f
incisure=incisura|f
space=espaço|m
content=conteúdo|m
compartment=compartimento|m
boundary=limite|m
entity=entidade|f
structure=estrutura|f
junction=junção|f
line=linha|f
continuity=continuidade|f
anastomosis=anastomose|f
process=processo|m
concha=concha|f
trochlea=tróclea|f
decussation=decussação|f
bronchus=brônquio|m
myocardium=miocárdio|m
musculature=musculatura|f
skeleton=esqueleto|m
column=coluna|f
cage=caixa|f
back=dorso|m
dorsum=dorso|m
cord=cordão|m
limb=membro|m
girdle=cintura|f
network=rede|f
apparatus=aparelho|m
formation=formação|f
cortex=córtex|m
subcortex=subcórtex|m
archicortex=arquicórtex|m
tectum=teto|m
complex=complexo|m
parenchyma=parênquima|m
integument=tegumento|m
appendage=anexo|m
epithelium=epitélio|m
epidermis=epiderme|f
vasculature=vascularização|f
conus=cone|m
curtain=cortina|f
disk=disco|m
symphysis=sínfise|f
''',N)
rows('''
posterior=posterior
anterior=anterior
superior=superior
inferior=inferior
lateral=lateral
medial=medial
middle=médio
basal=basal
apical=apical
segmental=segmentar
subsegmental=subsegmentar
bronchial=brônquico
bronchopulmonary=broncopulmonar
hepatic=hepático
biliary=biliar
cerebral=cerebral
thoracic=torácico
cervical=cervical
lumbar=lombar
sacral=sacral
costal=costal
intercostal=intercostal
intervertebral=intervertebral
metacarpal=metacarpal
metatarsal=metatarsal
carpal=carpal
tarsal=tarsal
palmar=palmar
plantar=plantar
digital=digital
coronary=coronário
secondary=permanente
upper=superior
lower=inferior
internal=interno
external=externo
common=comum
proper=próprio
temporal=temporal
frontal=frontal
parietal=parietal
occipital=occipital
renal=renal
cerebellar=cerebelar
dorsal=dorsal
superficial=superficial
deep=profundo
portal=portal
iliac=ilíaco
interventricular=interventricular
venous=venoso
pulmonary=pulmonar
major=maior
minor=menor
genicular=genicular
ulnar=ulnar
femoral=femoral
oblique=oblíquo
interosseous=interósseo
lacrimal=lacrimal
distal=distal
proximal=proximal
tibial=tibial
phrenic=frênico
epigastric=epigástrico
arytenoid=aritenóideo
acromial=acromial
cardiac=cardíaco
central=central
brachial=braquial
recurrent=recorrente
descending=descendente
ascending=ascendente
callosomarginal=calosomarginal
radial=radial
lingular=lingular
humeral=umeral
nasal=nasal
ventricular=ventricular
colic=cólico
cuneiform=cuneiforme
ciliary=ciliar
long=longo
short=curto
collateral=colateral
arterial=arterial
deltoid=deltoide
choroidal=coroidal
choroid=coroideo
pectoral=peitoral
thyrohyoid=tíreo-hióideo
transverse=transverso
scapular=escapular
investing=de revestimento
optic=óptico
obturator=obturatório
communicating=comunicante
mesenteric=mesentérico
pharyngeal=faríngeo
free=livre
papillary=papilar
suprarenal=suprarrenal
subclavian=subclávio
anatomical=anatômico
precentral=pré-central
postcentral=pós-central
carotid=carótido
perforating=perfurante
cricothyroid=cricotireóideo
intermediate=intermédio
pontine=pontino
caudate=caudado
median=mediano
pancreaticoduodenal=pancreaticoduodenal
orbital=orbital
frontobasal=frontobasal
vertebral=vertebral
popliteal=poplíteo
axillary=axilar
lobar=lobar
oculomotor=oculomotor
nasociliary=nasociliar
ophthalmic=oftálmico
spinal=espinal
pericallosal=pericaloso
saphenous=safeno
small=pequeno
large=grande
subscapular=subescapular
marginal=marginal
pancreatic=pancreático
gluteal=glúteo
systemic=sistêmico
ethmoidal=etmoidal
calcaneal=calcâneo
fibular=fibular
costocervical=costocervical
thyrocervical=tireocervical
tricuspid=tricúspide
aortic=aórtico
gastric=gástrico
pudendal=pudendo
tendinous=tendíneo
splenial=esplenial
terminal=terminal
prefrontal=pré-frontal
mitral=mitral
brachiocephalic=braquiocefálico
vascular=vascular
intrapulmonary=intrapulmonar
intrinsic=intrínseco
white=branco
gray=cinzento
thyroid=tireóideo
basilic=basílico
main=principal
clavicular=clavicular
pelvic=pélvico
posteromedial=posteromedial
bony=ósseo
infratrochlear=infratroclear
nasolacrimal=nasolacrimal
supratrochlear=supratroclear
trochlear=troclear
vitreous=vítreo
iliotibial=iliotibial
anal=anal
anterolateral=anterolateral
thalamogeniculate=talamogeniculado
polar=polar
thalamoperforating=talamoperfurante
vermian=vermiano
cingulate=do cíngulo
fusiform=fusiforme
parahippocampal=para-hipocampal
supramarginal=supramarginal
arcuate=arqueado
cephalic=cefálico
antebrachial=antebraquial
cubital=cubital
alar=alar
splenic=esplênico
pterygomandibular=pterigomandibular
sublingual=sublingual
submandibular=submandibular
corniculate=corniculado
vocal=vocal
adrenal=suprarrenal
deferent=deferente
seminal=seminal
palatine=palatino
zygomatic=zigomático
iliolumbar=iliolombar
urinary=urinário
skeletal=esquelético
sphenoid=esfenoide
fibrous=fibroso
epiglottic=epiglótico
subsuperior=subsuperior
sesamoid=sesamoide
cecal=cecal
gastroduodenal=gastroduodenal
gastroepiploic=gastro-omental
epiploic=omental
rectal=retal
cranial=craniano
postvertebral=pós-vertebral
extrinsic=extrínseco
nervous=nervoso
hypothalamic=hipotalâmico
postcommunicating=pós-comunicante
precommunicating=pré-comunicante
cardinal=principal
abdominal=abdominal
perineal=perineal
celiac=celíaco
coeliac=celíaco
hemiazygos=hemiázigos
ileal=ileal
ureteric=uretérico
variant=variante
accessory=acessório
parasympathetic=parassimpático
connective=conjuntivo
tracheobronchial=traqueobrônquico
navicular=navicular
sternocostal=esternocostal
straight=reto
intermediomedial=intermediomedial
paracentral=paracentral
precuneal=do pré-cúneo
insular=insular
lobular=lobular
suspensory=suspensor
respiratory=respiratório
apicoposterior=apicoposterior
gastrointestinal=gastrointestinal
cartilaginous=cartilagíneo
osseous=ósseo
myocardial=miocárdico
innermost=íntimo
basilar=basilar
interpeduncular=interpeduncular
mammillary=mamilar
mediobasal=mediobasal
laterobasal=laterobasal
oesophageal=esofágico
esophageal=esofágico
sigmoid=sigmoide
azygos=ázigos
autonomic=autônomo
irregular=irregular
salivary=salivar
neural=neural
cavernous=cavernoso
peritoneal=peritoneal
visceral=visceral
suboccipital=suboccipital
vertical=vertical
cavitated=cavitário
heterogeneous=heterogêneo
caval=caval
cell=celular
subarachnoid=subaracnóideo
axial=axial
inferomedial=inferomedial
limbic=límbico
patellar=patelar
subendocardial=subendocárdico
pulmopleural=pulmopleural
hippocampal=hipocampal
pineal=pineal
ileocecal=ileocecal
uvular=uvular
pubic=púbico
cystic=cístico
xiphoid=xifoide
caudal=caudal
flat=plano
pneumatized=pneumatizado
true=verdadeiro
typical=típico
false=falso
floating=flutuante
atypical=atípico
conduit=de condução
cricoid=cricoide
infrahyoid=infra-hióideo
extrahepatic=extra-hepático
appendicular=apendicular
loose=frouxo
mucoid=mucoide
nonskeletal=não esquelético
prevertebral=pré-vertebral
suprahyoid=supra-hióideo
ocular=ocular
trigeminal=trigeminal
laryngeal=laríngeo
hyoid=hioide
parenchymatous=parenquimatoso
corticomedullary=corticomedular
nonparenchymatous=não parenquimatoso
solid=sólido
hollow=oco
auriculotemporal=auriculotemporal
physical=físico
serous=seroso
thenar=tenar
hypothenar=hipotenar
immaterial=imaterial
material=material
articular=articular
facial=facial
intracranial=intracraniano
supreme=supremo
membranous=membranáceo
nuclear=nuclear
circumventricular=circunventricular
alimentary=alimentar
genital=genital
cardiovascular=cardiovascular
musculoskeletal=musculoesquelético
subaortic=subaórtico
endocrine=endócrino
sternal=esternal
mandibular=mandibular
maxillary=maxilar
faucial=das fauces
intrahepatic=intra-hepático
integumentary=tegumentar
fascial=fascial
pancreaticobiliary=pancreatobiliar
basicranial=da base do crânio
angular=angular
geniculate=geniculado
subcostal=subcostal
musculophrenic=musculofrênico
suprascapular=supraescapular
thoracodorsal=toracodorsal
diagonal=diagonal
testicular=testicular
hepatovenous=hepatovenoso
ileocolic=ileocólico
septal=septal
j ugular=jugular
jugular=jugular
great=magno
circumflex=circunflexo
rotator=rotador
''',A)
M={}
rows('''
abductor hallucis=abdutor do hálux
abductor pollicis brevis=abdutor curto do polegar
abductor pollicis longus=abdutor longo do polegar
adductor brevis=adutor curto
adductor longus=adutor longo
adductor magnus=adutor magno
adductor minimus=adutor mínimo
adductor hallucis=adutor do hálux
adductor pollicis=adutor do polegar
anconeus=ancôneo
aryepiglotticus=ariepiglótico
brachialis=braquial
brachioradialis=braquiorradial
coracobrachialis=coracobraquial
coccygeus=coccígeo
digastric=digástrico
external oblique=oblíquo externo do abdome
internal oblique=oblíquo interno do abdome
transversus abdominis=transverso do abdome
rectus abdominis=reto do abdome
extensor carpi radialis brevis=extensor radial curto do carpo
extensor carpi radialis longus=extensor radial longo do carpo
extensor carpi ulnaris=extensor ulnar do carpo
extensor digiti minimi=extensor do dedo mínimo
extensor digitorum=extensor dos dedos
extensor digitorum longus=extensor longo dos dedos
extensor digitorum brevis=extensor curto dos dedos
extensor hallucis brevis=extensor curto do hálux
extensor hallucis longus=extensor longo do hálux
extensor indicis=extensor do indicador
extensor pollicis brevis=extensor curto do polegar
extensor pollicis longus=extensor longo do polegar
fibularis brevis=fibular curto
fibularis longus=fibular longo
fibularis tertius=fibular terceiro
flexor accessorius=quadrado plantar
flexor carpi radialis=flexor radial do carpo
flexor carpi ulnaris=flexor ulnar do carpo
flexor digitorum brevis=flexor curto dos dedos
flexor digitorum longus=flexor longo dos dedos
flexor digitorum profundus=flexor profundo dos dedos
flexor digitorum superficialis=flexor superficial dos dedos
flexor hallucis brevis=flexor curto do hálux
flexor hallucis longus=flexor longo do hálux
flexor pollicis brevis=flexor curto do polegar
flexor pollicis longus=flexor longo do polegar
flexor digiti minimi brevis=flexor curto do dedo mínimo
abductor digiti minimi=abdutor do dedo mínimo
opponens digiti minimi=oponente do dedo mínimo
opponens pollicis=oponente do polegar
gastrocnemius=gastrocnêmio
gemellus=gêmeo
gemellus inferior=gêmeo inferior
gemellus superior=gêmeo superior
genioglossus=genioglosso
geniohyoid=gênio-hióideo
gluteus maximus=glúteo máximo
gluteus medius=glúteo médio
gluteus minimus=glúteo mínimo
gracilis=grácil
hyoglossus=hioglosso
iliacus=ilíaco
iliococcygeus=iliococcígeo
iliocostalis=iliocostal
iliocostalis cervicis=iliocostal do pescoço
iliocostalis lumborum=iliocostal do lombo
iliocostalis thoracis=iliocostal do tórax
infraspinatus=infraespinal
interspinalis thoracis=interespinal do tórax
interspinalis=interespinal
interspinales=interespinais
intertransversarius=intertransversário
intertransversarii=intertransversários
levator ani=levantador do ânus
levator palpebrae superioris=levantador da pálpebra superior
levator scapulae=levantador da escápula
levator veli palatini=levantador do véu palatino
levatores costarum=levantadores das costelas
levatores costarum breves=levantadores curtos das costelas
levatores costarum longi=levantadores longos das costelas
longissimus=longuíssimo
longissimus capitis=longuíssimo da cabeça
longissimus cervicis=longuíssimo do pescoço
longissimus thoracis=longuíssimo do tórax
longus capitis=longo da cabeça
longus colli=longo do pescoço
lumbrical=lumbrical
lumbricals=lumbricais
mylohyoid=milo-hióideo
obliquus capitis inferior=oblíquo inferior da cabeça
obliquus capitis superior=oblíquo superior da cabeça
obturator externus=obturador externo
obturator internus=obturador interno
omohyoid=omo-hióideo
palatopharyngeus=palatofaríngeo
palmaris longus=palmar longo
pectineus=pectíneo
pectoralis major=peitoral maior
pectoralis minor=peitoral menor
piriformis=piriforme
plantaris=plantar
platysma=platisma
popliteus=poplíteo
pronator quadratus=pronador quadrado
pronator teres=pronador redondo
psoas major=psoas maior
pubococcygeus=pubococcígeo
puborectalis=puborretal
quadratus femoris=quadrado femoral
quadratus lumborum=quadrado lombar
rectus capitis anterior=reto anterior da cabeça
rectus capitis lateralis=reto lateral da cabeça
rectus capitis posterior major=reto posterior maior da cabeça
rectus capitis posterior minor=reto posterior menor da cabeça
rectus femoris=reto femoral
rhomboid major=romboide maior
rhomboid minor=romboide menor
salpingopharyngeus=salpingofaríngeo
sartorius=sartório
scalenus anterior=escaleno anterior
scalenus medius=escaleno médio
scalenus posterior=escaleno posterior
semimembranosus=semimembranáceo
semispinalis=semiespinal
semispinalis capitis=semiespinal da cabeça
semispinalis cervicis=semiespinal do pescoço
semispinalis thoracis=semiespinal do tórax
semitendinosus=semitendíneo
serratus anterior=serrátil anterior
serratus posterior=serrátil posterior
serratus posterior inferior=serrátil posterior inferior
serratus posterior superior=serrátil posterior superior
soleus=sóleo
spinalis=espinal
spinalis thoracis=espinal do tórax
splenius=esplênio
splenius capitis=esplênio da cabeça
splenius cervicis=esplênio do pescoço
sternocleidomastoid=esternocleidomastóideo
sternohyoid=esterno-hióideo
sternothyroid=esternotireóideo
stylohyoid=estilo-hióideo
stylopharyngeus=estilofaríngeo
subclavius=subclávio
subscapularis=subescapular
supinator=supinador
supraspinatus=supraespinal
tensor fasciae latae=tensor da fáscia lata
tensor veli palatini=tensor do véu palatino
teres major=redondo maior
teres minor=redondo menor
thyrohyoid=tíreo-hióideo
tibialis anterior=tibial anterior
tibialis posterior=tibial posterior
transversus thoracis=transverso do tórax
trapezius=trapézio
vastus intermedius=vasto intermédio
vastus lateralis=vasto lateral
vastus medialis=vasto medial
vocalis=vocal
biceps brachii=bíceps braquial
biceps femoris=bíceps femoral
triceps brachii=tríceps braquial
quadriceps femoris=quadríceps femoral
cricothyroid=cricotireóideo
pharyngeal constrictor=constritor da faringe
superior pharyngeal constrictor=constritor superior da faringe
middle pharyngeal constrictor=constritor médio da faringe
inferior pharyngeal constrictor=constritor inferior da faringe
''',M)
for k,v in list(M.items()):
    plural=k in ['interspinales','intertransversarii','lumbricals'] or k.startswith('levatores ')
    D[k]=('músculos ' if plural else 'músculo ')+v+('|mp' if plural else '|m')
    D[k+' muscle']=D[k]
N.update({k:v for k,v in D.items()})
rows('''
deltoid=músculo deltoide|m
cervical rotator=músculo rotador cervical|m
lumbar rotator=músculo rotador lombar|m
thoracic rotator=músculo rotador torácico|m
interosseous=músculo interósseo|m
plantar interosseous=músculo interósseo plantar|m
dorsal interossei=músculos interósseos dorsais|mp
palmar interossei=músculos interósseos palmares|mp
external anal sphincter=músculo esfíncter externo do ânus|m
arteria princeps pollicis=artéria principal do polegar|f
arteria radialis indicis=artéria radial do indicador|f
dorsalis pedis artery=artéria dorsal do pé|f
cerebral arterial circle=círculo arterial do cérebro|m
chest wall=parede torácica|f
body wall=parede do corpo|f
rib cage=caixa torácica|f
body cavity content=conteúdo da cavidade corporal|m
body compartment=compartimento corporal|m
bone organ=osso como órgão|m
muscle organ=músculo como órgão|m
cartilage organ=cartilagem como órgão|f
ligament organ=ligamento como órgão|m
membrane organ=membrana como órgão|f
cartilage organ component=componente cartilagíneo de órgão|m
ligament organ component=componente ligamentar de órgão|m
membrane organ component=componente membranoso de órgão|m
organ component gland=glândula componente de órgão|f
organ component layer=camada componente de órgão|f
organ component cluster=agrupamento de componentes de órgão|m
organ part cluster=agrupamento de partes de órgão|m
organ cavity subdivision=subdivisão da cavidade de órgão|f
anatomical boundary entity=limite anatômico|m
anatomical compartment space=espaço de compartimento anatômico|m
cardinal tissue part=parte principal de tecido|f
cardinal body part=parte principal do corpo|f
cell part cluster=agrupamento de partes celulares|m
midbrain tectum=teto do mesencéfalo|m
fascia lata=fáscia lata|f
flexor retinaculum=retináculo dos flexores|m
inflow part=via de entrada|f
outflow part=via de saída|f
internal gray matter component=componente interno de substância cinzenta|m
pancreatic duct tree=árvore de ductos pancreáticos|f
hepatic biliary tree=árvore biliar hepática|f
coronary sinus tree=árvore do seio coronário|f
vascular tree organ=órgão vascular ramificado|m
arterial tree organ=órgão arterial ramificado|m
venous tree organ=órgão venoso ramificado|m
neural tree organ=órgão neural ramificado|m
hollow tree organ=órgão oco ramificado|m
pulmonary venous tree organ=órgão venoso pulmonar ramificado|m
superior vena caval tree=árvore da veia cava superior|f
inferior vena caval tree=árvore da veia cava inferior|f
caudate lobe branch=ramo do lobo caudado|m
left lobe branch=ramo do lobo esquerdo|m
right lobe branch=ramo do lobo direito|m
caudate lobe tributary=tributária do lobo caudado|f
upper lobe part=parte do lobo superior|f
middle lobe part=parte do lobo médio|f
lower lobe part=parte do lobo inferior|f
organ regions=regiões de órgão|fp
skin appendage=anexo da pele|m
side=lado|m
root=raiz|f
palate=palato|m
muscle layer=camada muscular|f
check ligament=ligamento de contenção|m
conus artery=artéria do cone|f
conus branch=ramo do cone|m
''',D)
N.update(D)
rows('''
antero-medial=anteromedial
cervicis=cervical
lumborum=lombar
cuboid=cuboide
extra-ocular=extraocular
constrictor=constritor
medullaris=medular
pre-hepatic=pré-hepático
scalene=escaleno
stylohyoid=estilo-hióideo
''',A)
ORD={k:str(i) for i,k in enumerate('first second third fourth fifth sixth seventh eighth ninth tenth eleventh twelfth'.split(),1)}
def agree(a,g):
    if g.startswith('f'):
        if a.endswith('o'):a=a[:-1]+'a'
        elif a.endswith('or'): a += 'a' if a in ['suspensor','oculomotor','rotador'] else ''
    if g.endswith('p') and not a.startswith(('de ','do ','da ','das ')):
        if a.endswith('l'): a=a[:-1]+'is'
        elif a.endswith(('r','z')):a+='es'
        elif not a.endswith('s'):a+='s'
    return a
def prep(pt,g,kind='of'):
    article={'m':'o','f':'a','mp':'os','fp':'as'}[g]
    return ('d'+article if kind=='of' else 'para '+article)+' '+pt
def exact(s):
    if s in D:return tuple(D[s].rsplit('|',1))
    if s in N:return tuple(N[s].rsplit('|',1))
def mods(s,g):
    if not s:return ''
    # These compound anatomical adjectives have an established single translation.
    compounds={'thoraco-acromial':'toracoacromial','gastro-epiploic':'gastro-omental','supra-orbital':'supraorbital','temporo-occipital':'temporoccipital','hyo-epiglottic':'hioepiglótico','thyro-epiglottic':'tireoepiglótico','pre-frontal':'pré-frontal','antero-lateral':'anterolateral','bile':'biliar','organ':'orgânico','organ part':'de partes de órgão','nerve':'nervoso'}
    if s in compounds:return agree(compounds[s],g)
    out=[]
    for w in reversed(s.split()):
        if w in ORD:out.insert(0,ORD[w]+('ª' if g.startswith('f') else 'º'))
        elif w in ['right','left']:out.append(agree('direito' if w=='right' else 'esquerdo',g))
        elif w in A:out.append(agree(A[w],g))
        elif re.fullmatch(r'[ivx]+|\d+',w):out.append(w.upper())
        elif w in compounds:out.append(agree(compounds[w],g))
        else:missing.add(w);out.append('['+w+']')
    return ' '.join(out)
def tr(s):
    s=s.lower().strip().replace('subdivisionof ','subdivision of ').replace('(in-vivo)','(in vivo)')
    if exact(s):return exact(s)
    for sep,kind in [(' of ','of'),(' to ','to'),(' with ','with')]:
        if sep in s:
            l,r=s.split(sep,1);lp,lg=tr(l);rp,rg=tr(r)
            return lp+' '+('com '+rp if kind=='with' else prep(rp,rg,kind)),lg
    if s.endswith(' (in vivo)'):
        p,g=tr(s[:-10]);return p+' (in vivo)',g
    # Side and ordinal are grammatical modifiers of the complete structure.
    m=re.match(r'^(right|left) (.*)$',s)
    if m:
        p,g=tr(m[2]);return p+' '+agree('direito' if m[1]=='right' else 'esquerdo',g),g
    m=re.match(r'^('+ '|'.join(ORD)+r') (.*)$',s)
    if m:
        p,g=tr(m[2]);return ORD[m[1]]+('ª' if g.startswith('f') else 'º')+' '+p,g
    m=re.match(r'^(.*) (\d+|[ivx]+)$',s)
    if m:
        p,g=tr(m[1]);return p+' '+m[2].upper(),g
    if s.endswith(' proper'):
        p,g=tr(s[:-7]);return p+' '+agree('próprio',g),g
    # Prefer the longest noun phrase; reverse English premodifiers into Portuguese.
    for key in sorted(N,key=len,reverse=True):
        if s.endswith(' '+key):
            p,g=exact(key);prefix=s[:-len(key)-1]
            return p+' '+mods(prefix,g),g
    # Handle nouns followed by a Latin or English qualifier (e.g. muscle groups).
    for key in sorted(N,key=len,reverse=True):
        if s.startswith(key+' '):
            p,g=exact(key);return p+' '+mods(s[len(key)+1:],g),g
    missing.add(s);return '['+s+']','m'
def build():
    data=json.loads((ROOT/'public/models/atlas.json').read_text())
    names=sorted(set(p['name'].lower() for p in data['parts']+data['concepts']))
    result={n:tr(n)[0] for n in names}
    # Portuguese ordinals precede the noun even when English places a location first.
    result={n:re.sub(r'^(.+?) (\d+[ºª]) ',r'\2 \1 ',pt) if 'tooth' in n else pt for n,pt in result.items()}
    if missing:raise ValueError('Untranslated terms: '+', '.join(sorted(missing)))
    (ROOT/'app/pt-br.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
    print('Labels:',len(result),'Untranslated:',len(missing))
    print('\n'.join(sorted(missing)))
if __name__=='__main__':build()
