import {useState} from 'react';import {ArrowLeft,ArrowUpRight,Eye,EyeOff,LockKeyhole,Mail} from 'lucide-react';
import {Button} from '@/components/ui/button';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Brand} from './brand';import {api,type Session} from './api';
const DEMO_ACCOUNTS=[
 {key:'juan',login:'demo@anatomed.com',email:'demo@anatomed.com',password:'Anatomed2026!',name:'Juan — demonstração'},
 {key:'mayne',login:'mayne',email:'mayne@anatomed.com',password:'anatomedmay',name:'Mayne — influencer'}
] as const;
export default function AuthView({session}:{session:Session}){const [mode,setMode]=useState<'login'|'signup'|'recover'>('login'),[visible,show]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[role,setRole]=useState('student');
 const demoMode=!session.authConfigured;
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setError('');setMessage('');setBusy(true);const f=new FormData(e.currentTarget);try{const email=String(f.get('email')||'').trim().toLowerCase(),password=String(f.get('password')||'');
   if(demoMode){if(mode!=='login'){setError('O cadastro real será liberado quando o Supabase for conectado. Use um dos acessos de demonstração para conhecer a área interna.');return;}const account=DEMO_ACCOUNTS.find(x=>(email===x.login||email===x.email)&&password===x.password);if(!account){setError('Para a demonstração, use um dos logins e senhas exibidos acima.');return;}sessionStorage.setItem('anatomed_demo_access','1');sessionStorage.setItem('anatomed_demo_account',account.key);location.assign('/estudar');return;}
   const result=await api('/auth/'+mode,{method:'POST',body:JSON.stringify({email,password,name:f.get('name'),role})});if(result.message)setMessage(result.message);else location.assign('/estudar');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="access-page"><aside className="access-aside"><Brand light/><div><p className="overline">BEM-VINDO À SUA PRÓXIMA PERSPECTIVA</p><h1>Conhecer<br/>por dentro.<br/><span>Aprender<br/>de verdade.</span></h1><p>Seu atlas. Seu caderno.<br/>Seu espaço para fazer conexões.</p></div><small>Anatomed · Anatomia para aprender e ensinar.</small></aside><main className="access-main"><a className="back-link" href="/"><ArrowLeft size={16}/> Voltar ao Anatomed</a><div className="access-form"><span className="section-number">{mode==='signup'?'COMECE POR AQUI':'SEU ESPAÇO DE ESTUDO'}</span><h2>{mode==='login'?'Bom ter você aqui.':mode==='signup'?'Uma nova perspectiva.':'Vamos recuperar seu acesso.'}</h2><p>{mode==='login'?'Entre para continuar de onde parou.':mode==='signup'?'Crie sua conta de estudante ou professor.':'Enviaremos as instruções para o e-mail cadastrado.'}</p>
 {!session.authConfigured&&<div className="notice demo-access-notice"><LockKeyhole size={18}/><div><strong>Acessos de demonstração liberados</strong><br/>Login: <code>demo@anatomed.com</code> · Senha: <code>Anatomed2026!</code><br/>Login Mayne: <code>mayne</code> · Senha: <code>anatomedmay</code><br/><small>Esses acessos são temporários para revisar a área interna antes da conexão com o Supabase.</small></div></div>}
 <form onSubmit={submit}>{mode==='signup'&&<div className="field"><Label htmlFor="name">Seu nome</Label><Input id="name" name="name" autoComplete="name" required maxLength={100}/></div>}<div className="field"><Label htmlFor="email">{demoMode?'Login ou e-mail':'E-mail ou login'}</Label><Input id="email" name="email" type="text" autoComplete={demoMode?'username':'email'} placeholder={demoMode?'mayne ou demo@anatomed.com':'voce@exemplo.com ou mayne'} required maxLength={254}/></div>{mode!=='recover'&&<div className="field"><div className="label-row"><Label htmlFor="password">Senha</Label>{mode==='login'&&<button type="button" onClick={()=>{setMode('recover');setError('');}}>Esqueci minha senha</button>}</div><div className="password-field"><Input id="password" name="password" type={visible?'text':'password'} autoComplete={mode==='signup'?'new-password':'current-password'} required minLength={mode==='signup'?10:1} maxLength={128}/><button type="button" aria-label={visible?'Ocultar senha':'Mostrar senha'} onClick={()=>show(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{mode==='signup'&&<small>Use pelo menos 10 caracteres.</small>}</div>}{mode==='signup'&&<div className="field"><Label>Como você vai usar o Anatomed?</Label><RadioGroup value={role} onValueChange={v=>setRole(v as string)} className="role-options"><Label><RadioGroupItem value="student"/> Sou estudante</Label><Label><RadioGroupItem value="teacher"/> Sou professor(a)</Label></RadioGroup></div>}
 {error&&<p className="form-error" role="alert">{error}</p>}{message&&<p className="form-success" role="status">{message}</p>}<Button className="button dark full" type="submit" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar no Anatomed':mode==='signup'?'Criar minha conta':'Enviar instruções'}<ArrowUpRight size={18}/></Button></form>
 <div className="auth-switch">{mode==='login'?<>Ainda não tem conta? <button onClick={()=>{setMode('signup');setError('');}}>Criar conta</button></>:<button onClick={()=>{setMode('login');setError('');}}>Voltar para o login</button>}</div><a className="owner-entry" href="/admin">Acesso do proprietário <ArrowUpRight size={14}/></a></div></main></div>;
}

