import {lazy,Suspense,useState} from 'react';
import {ArrowUpRight,ArrowRight,MoveUpRight,Box,NotebookPen,BookOpen,Search,Check,Pause,Play,Layers3,Menu,X,ChevronDown} from 'lucide-react';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {Button} from '@/components/ui/button';
import {Brand} from './brand';import {money,type Session} from './api';
const Hero=lazy(()=>import('./hero'));
export default function Landing({session}:{session:Session}){const [separated,split]=useState(false),[paused,pause]=useState(false),[menu,open]=useState(false);const settings=session.settings;
 return <div className="marketing">
  <header className="site-header"><Brand/><nav className={menu?'is-open':''}><a href="#experiencia" onClick={()=>open(false)}>A experiência</a><a href="#estudo" onClick={()=>open(false)}>Para estudar</a><a href="#acesso" onClick={()=>open(false)}>Seu acesso</a></nav><div className="header-cta"><a href={session.user?'/estudar':'/entrar'} className="text-link">{session.user?'Meu espaço':'Entrar'} <ArrowUpRight size={16}/></a><a className="button dark small desktop-link" href="#acesso">Começar agora</a><Button variant="ghost" className="menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} onClick={()=>open(!menu)}>{menu?<X/>:<Menu/>}</Button></div></header>
  <main><section className="hero-section" id="experiencia"><div className="hero-copy"><p className="overline"><span className="tiny-cross">+</span> SEU PRÓXIMO NÍVEL EM ANATOMIA</p><h1>Anatomia<br/>em outra<br/><span>dimensão.</span></h1><p className="hero-description">Explore o corpo. Conecte as ideias.<br/>Transforme o que você vê em conhecimento.</p><div className="hero-buttons"><a href="#acesso" className="button dark">Quero estudar assim <ArrowUpRight size={19}/></a><a href="/demonstracao" className="hero-secondary">Experimentar o 3D <ArrowRight size={17}/></a></div><div className="hero-audience"><span className="audience-rule"/><p>Para estudantes e professores<br/><strong>de Medicina e das Ciências da Saúde.</strong></p></div></div>
   <div className="hero-visual"><span className="hero-background-word" aria-hidden="true">HUMANO</span><div className="visual-topline"><span>ESTUDO 001 / CORPO HUMANO</span><span>VISUALIZAÇÃO 3D</span></div><Suspense fallback={<div className="art-state">Preparando o modelo 3D…</div>}><Hero separated={separated} paused={paused}/></Suspense><div className="model-label"><span>01</span><div>Uma nova perspectiva.<small>Arraste o corpo para explorar.</small></div></div><div className="visual-controls"><button className={separated?'is-active':''} onClick={()=>split(!separated)}><Layers3 size={15}/>{separated?'Reunir corpo':'Revelar camadas'}</button><button onClick={()=>pause(!paused)} aria-label={paused?'Ativar movimento':'Pausar movimento'}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></div></div>
  </section>
  <div className="proof-strip"><div><strong>2.234</strong><span>peças para explorar</span></div><div><strong>15</strong><span>sistemas anatômicos</span></div><div><strong>3D</strong><span>modelo colorido e detalhado</span></div><p>Observe. Entenda.<br/><b>Faça conexões.</b></p></div>
  <section className="study-section section-container" id="estudo"><div className="section-heading"><p className="overline">MUITO ALÉM DE MEMORIZAR</p><h2>Veja o todo.<br/><span>Entenda cada parte.</span></h2><p>Um espaço para explorar, revisar e construir o seu próprio raciocínio — da primeira aula à preparação da próxima.</p></div><div className="feature-grid">{[{n:'01',icon:Box,t:'Explore em 3D',d:'Gire, aproxime, separe e isole estruturas. Descubra as relações que uma imagem plana nem sempre mostra.'},{n:'02',icon:BookOpen,t:'Revise o essencial',d:'Resumos por sistema, pontos-chave e sugestões práticas para orientar a exploração do atlas.'},{n:'03',icon:NotebookPen,t:'Escreva do seu jeito',d:'Crie um caderno com suas anotações. Relacione cada registro à estrutura que você está estudando.'},{n:'04',icon:Search,t:'Vá até a fonte',d:'Acesse publicações e pesquise por assunto no Google Acadêmico e no PubMed.'}].map(f=><article className="feature" key={f.n}><div className="feature-top"><f.icon strokeWidth={1.3} size={29}/><span>{f.n}</span></div><h3>{f.t}</h3><p>{f.d}</p></article>)}</div></section>
  <section className="method-section"><div className="section-container method-inner"><p className="overline">SEU JEITO DE APRENDER. EM UM SÓ LUGAR.</p><div className="method-layout"><h2>Da curiosidade<br/>à compreensão<span>.</span></h2><ol><li><span>01</span><div><h3>Escolha uma estrutura.</h3><p>Use o atlas para descobrir sua forma, localização e contexto.</p></div></li><li><span>02</span><div><h3>Conecte com a teoria.</h3><p>Revise o sistema e consulte referências para aprofundar o assunto.</p></div></li><li><span>03</span><div><h3>Registre o que entendeu.</h3><p>Escreva uma síntese com suas próprias palavras e retome depois.</p></div></li></ol></div></div></section>
  <section className="offer-section section-container" id="acesso"><div className="offer-copy"><p className="overline">UM INVESTIMENTO NO SEU ESTUDO</p><h2>Menos decoreba.<br/><span>Mais perspectiva.</span></h2><p>{settings.headline}</p><p className="offer-for">Para quem estuda. Para quem ensina.<br/>Uma conta individual para explorar e organizar seu conhecimento.</p></div><div className="offer-card"><div className="offer-tag">ACESSO INDIVIDUAL <ArrowUpRight size={20}/></div><h3>Seu Anatomed.</h3><div className="price"><strong>{money(settings.price)}</strong><span>pagamento único</span></div><ul>{['Atlas completo em 3D','10 resumos iniciais por sistema','Caderno pessoal de anotações','Pesquisa no Google Acadêmico e PubMed','Conteúdo e interface em português'].map(x=><li key={x}><Check size={17}/>{x}</li>)}</ul><a className="button dark" href={settings.offerEnabled?(settings.checkoutUrl||'/entrar?compra=1'):'/entrar'}>{settings.checkoutUrl?'Quero meu acesso':'Conhecer meu acesso'}<ArrowUpRight size={18}/></a><small>Uso educacional. Conta pessoal e intransferível.</small></div></section>
  <section className="faq-section section-container"><div><p className="overline">ANTES DE COMEÇAR</p><h2>Alguma dúvida?</h2></div><Accordion className="faq-items">{[['Para quem é o Anatomed?','Para estudantes e professores de Medicina, Enfermagem, Fisioterapia, Nutrição e outras áreas da saúde que estudam anatomia humana.'],['O que está incluído no acesso?','O atlas 3D, os resumos iniciais, o caderno pessoal e os atalhos de pesquisa científica. A oferta é de acesso individual com pagamento único.'],['Funciona no celular?','A apresentação usa um modelo mais leve. O atlas completo exige mais memória e um navegador com suporte a 3D; o desempenho depende do aparelho. Para explorar muitos sistemas ao mesmo tempo, recomendamos uma tela maior.'],['Os conteúdos estão em português?','Sim. Os controles, nomes anatômicos e explicações estão em português brasileiro. Os nomes originais foram preservados para consulta. Artigos externos podem estar em outros idiomas.'],['O Anatomed substitui livros ou aulas?','O Anatomed é um recurso complementar de estudo. O modelo representa um corpo masculino adulto e não inclui todas as variações anatômicas. Os resumos não substituem a bibliografia da sua disciplina.']].map(([q,a],i)=><AccordionItem key={q} value={String(i)}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
  </main><footer className="site-footer"><Brand/><p>O corpo humano, sob uma nova perspectiva.</p><div><a href="/referencias">Fontes e créditos</a><a href="/admin">Administração</a></div><small>© {new Date().getFullYear()} Anatomed · Educação em anatomia.</small></footer>
 </div>;
}
