export const scholar=(query:string)=>'https://scholar.google.com/scholar?hl=pt-BR&q='+encodeURIComponent(query);
export const pubmed=(query:string)=>'https://pubmed.ncbi.nlm.nih.gov/?term='+encodeURIComponent(query);
export const lessons=[
 {id:'cardiac',title:'Coração e circulação',chapter:'19-introduction',query:'heart anatomy coronary circulation',intro:'Dois circuitos, uma circulação contínua.',points:['O circuito pulmonar leva sangue do ventrículo direito aos pulmões e o devolve ao átrio esquerdo.','O circuito sistêmico parte do ventrículo esquerdo, alcança os tecidos e retorna ao átrio direito.','As valvas orientam o fluxo. As artérias coronárias irrigam o próprio músculo cardíaco.'],task:'Localize as quatro cavidades e acompanhe o caminho do sangue. Compare a aorta com o tronco pulmonar.'},
 {id:'skeletal',title:'Ossos e articulações',chapter:'6-introduction',query:'bone anatomy skeletal system',intro:'A estrutura que sustenta e protege.',points:['O esqueleto axial reúne crânio, coluna vertebral e caixa torácica. O apendicular inclui cinturas e membros.','O osso é um tecido vivo: sustenta o corpo, protege órgãos e armazena minerais.','As articulações conectam ossos. Sua estrutura condiciona o tipo e a amplitude dos movimentos.'],task:'Isole o fêmur e a escápula. Compare a forma de um osso longo com a de um osso plano.'},
 {id:'muscular',title:'Músculos e movimento',chapter:'10-introduction',query:'skeletal muscle anatomy function',intro:'Da contração ao movimento.',points:['Músculos esqueléticos se ligam a estruturas por tendões ou outras inserções e produzem força ao se contrair.','Agonistas executam um movimento; antagonistas se opõem a ele; sinergistas auxiliam a ação.','Origem, inserção, trajeto e articulação atravessada ajudam a compreender a ação muscular.'],task:'Compare o bíceps e o tríceps braquiais. Observe em que lado da articulação do cotovelo cada um passa.'},
 {id:'nervous',title:'Sistema nervoso',chapter:'12-introduction',query:'central peripheral nervous system anatomy',intro:'Receber, integrar e responder.',points:['O sistema nervoso central compreende encéfalo e medula espinal. O periférico reúne nervos e gânglios.','Vias aferentes conduzem informação sensitiva ao sistema central; vias eferentes levam comandos aos efetores.','Neurônios transmitem sinais; células da glia sustentam e regulam o ambiente neural.'],task:'Localize encéfalo e medula espinal. Diferencie um nervo periférico de uma região do sistema central.'},
 {id:'respiratory',title:'Vias respiratórias',chapter:'22-introduction',query:'respiratory anatomy lungs gas exchange',intro:'O caminho do ar até o sangue.',points:['As vias de condução levam ar aos pulmões; as regiões respiratórias participam das trocas gasosas.','A traqueia se divide em brônquios. A árvore brônquica ramifica-se dentro dos pulmões.','A contração do diafragma aumenta o volume torácico e favorece a inspiração.'],task:'Siga a traqueia até os brônquios principais. Compare os lobos dos pulmões direito e esquerdo.'},
 {id:'digestive',title:'Sistema digestório',chapter:'23-introduction',query:'digestive system anatomy nutrient absorption',intro:'Transformar alimento em nutrientes disponíveis.',points:['O tubo digestório conduz, mistura e transforma o alimento. Seus movimentos também deslocam o conteúdo.','A maior parte da absorção de nutrientes ocorre no intestino delgado. O intestino grosso participa da absorção de água.','Fígado, vesícula biliar e pâncreas contribuem com secreções que auxiliam a digestão.'],task:'Identifique esôfago, estômago e intestinos. Observe a relação do fígado e do pâncreas com o duodeno.'},
 {id:'urinary',title:'Rins e vias urinárias',chapter:'25-introduction',query:'kidney urinary system anatomy nephron',intro:'Filtração e equilíbrio interno.',points:['Os rins regulam água, eletrólitos e equilíbrio ácido-base, além de produzirem urina.','No néfron, filtração, reabsorção e secreção contribuem para a composição final da urina.','A urina segue pelos ureteres até a bexiga e é eliminada pela uretra.'],task:'Localize os rins e acompanhe os ureteres. Diferencie ureter de uretra pelo trajeto e pela função.'},
 {id:'endocrine',title:'Comunicação hormonal',chapter:'17-introduction',query:'endocrine glands anatomy hormone regulation',intro:'Mensagens químicas que coordenam o organismo.',points:['Glândulas endócrinas liberam hormônios no sangue. A resposta depende de receptores presentes nas células-alvo.','Hipófise, tireoide e suprarrenais participam de diferentes eixos de regulação.','Mecanismos de retroalimentação ajudam a controlar a secreção hormonal.'],task:'Localize hipófise, tireoide e suprarrenais. Anote um hormônio associado a cada glândula.'},
 {id:'lymphatic',title:'Sistema linfático',chapter:'21-introduction',query:'lymphatic system anatomy immune organs',intro:'Drenagem dos tecidos e defesa.',points:['Vasos linfáticos recolhem parte do líquido intersticial e o devolvem à circulação venosa.','Linfonodos participam da vigilância imunológica da linfa. O baço filtra sangue.','O timo participa da maturação dos linfócitos T e é mais ativo nas primeiras fases da vida.'],task:'Localize baço e timo. Registre a diferença entre filtrar sangue e filtrar linfa.'},
 {id:'reproductive',title:'Anatomia reprodutora',chapter:'27-introduction',query:'male reproductive system anatomy',intro:'Estruturas do modelo masculino adulto.',points:['Testículos produzem espermatozoides e hormônios. Epidídimos participam da maturação e do armazenamento dos espermatozoides.','Ductos deferentes conduzem espermatozoides. Glândulas acessórias contribuem para a composição do sêmen.','O modelo atual representa anatomia masculina e não contempla todas as variações anatômicas.'],task:'Identifique testículos, epidídimos, ductos deferentes e próstata. Refaça o trajeto entre essas estruturas.'},
];
export const textbook=(chapter:string)=>'https://openstax.org/books/anatomy-and-physiology-2e/pages/'+chapter;
export const papers=[
 {title:'BodyParts3D: 3D structure database for anatomical concepts',year:'2009',author:'Mitsuhashi et al.',type:'Base anatômica',url:'https://doi.org/10.1093/nar/gkn613',description:'Publicação que apresenta a base de estruturas usada no atlas.'},
 {title:'Three-dimensional visualisation of authentic cases in anatomy learning',year:'2022',author:'Silén et al.',type:'Educação em anatomia',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC9210673/',description:'Estudo sobre a visualização tridimensional de casos no aprendizado de anatomia.'},
 {title:'3D visualization technology for learning human anatomy',year:'2024',author:'Wang et al.',type:'Revisão da literatura',url:'https://pubmed.ncbi.nlm.nih.gov/38671399/',description:'Pesquisa sobre tecnologias de visualização 3D no ensino de anatomia.'},
];
